name: Make release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: build
        cache-env: true
        cache-downloads: true
        environment-file: ./conda/build-env.yml
        channels: conda-forge,observatoire-mobilite

    - name: Checkout odmkraken source
      uses: actions/checkout@v3

    - name: version
      shell: bash -l {0}
      run: |
        RELEASE=$(python ./release.py version)
        
        VERSION=$(echo $RELEASE | sed s/+.*$//)
        BLDSTR=$(echo $RELEASE | sed s/^.*+//)
        PREREL=false; [[ $VERSION =~ (a|b|rc)[0-9]+$ ]] && PREREL=true
        
        echo "::set-output name=release::${RELEASE}"
        echo "::set-output name=version::${VERISON}"
        echo "::set-output name=buildstr::${BLDSTR}"
        echo "::set-output name=is_prerelease::${PREREL}"
        echo "::set-output name=buildnbr::1"
      id: version

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: ${{ steps.version.outputs.is_prerelease }}
        release_name: ${{ steps.version.outputs.release }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build odmkraken
      shell: bash -l {0}
      run: |
        conda config --set anaconda_upload yes
        mkdir ./dist
        conda mambabuild -c conda-forge -c observatoire-mobilite --numpy 1.21 --output-folder ./dist --user observatoire-mobilite --token ${{ secrets.ANACONDA_TOKEN }} ./conda
      env:
        REQUESTED_VERSION: ${{ steps.version.outputs.version }}
        REQUESTED_BUILD_STRING: ${{ steps.version.outputs.buildstr }}
        REQUESTED_BUILD_NUMBER: ${{ steps.version.outputs.buildnbr }}
        
    - name: Upload odmkraken package as artifact
      uses: actions/upload-artifact@v3
      with:
          path: ./dist/noarch/odmkraken-${{ steps.version.outputs.release }}-py_${{ steps.version.outputs.buildnbr }}.tar.bz2
