name: Build conda packages
on: [push]
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout odmkraken source
      uses: actions/checkout@v3
      
    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: build
        cache-env: true
        cache-downloads: true
        environment-file: false
        channels: conda-forge,observatoire-mobilite
        extra-specs: |
          python=3.10
          conda-build>=3.22
          boa
          anaconda-client
          invoke
        
    - name: Build odmkraken
      shell: bash -l {0}
      run: |
        mkdir ./dist
        conda mambabuild ./conda --skip-existing --output-folder ./dist
      env:
        REQUESTED_VERSION: 0.1.0a4
        REQUESTED_BUILD_NUMBER: 0
        
    - name: Upload odmkraken package as artifact
      uses: actions/upload-artifact@v3
      with:
          path: ./dist/odmkraken-*.tar.bz2