name: Run live tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: kartoza/postgis:14-3.1
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
          ALLOW_IP_RANGE: 0.0.0.0/0
          POSTGRES_MULTIPLE_EXTENSIONS: postgis,postgis_topology,postgis_raster,pgrouting
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        python-version: ["3.10"]  # removed python 3.8 and 3.9 to save on GitHub action credits
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: test
        cache-env: true
        environment-file: false
        channels: conda-forge,observatoire-mobilite
        extra-specs: |
          python=${{ matrix.python-version }}
          pytest
          pytest-cov
          pytest-mock
          psycopg2
          dagster>=1.0.10
          mapmatcher
          pandas
          fastparquet
          paramiko
          geopandas
    
    - name: Set up database
      id: db
      shell: bash -l {0}
      run: |
        python -m odmkraken.deploy setup --dbname edmo
        echo  "dsn_edmo_aoo=$(python -m odmkraken.deploy resetpw edmo_aoo --dsn)/edmo" >> $GITHUB_OUTPUT
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASS: postgres
        PYTHONPATH: ./src
        
    - name: Import road map
      shell: bash -l {0}
      run: |
        echo "{ops: {load_edges: {config: {network_edge_file: '${EDGES_FILE}'}}, load_nodes: {config: {network_node_file: '${NODES_FILE}'}}}, resources: {local_postgres: {config: {dsn: {env: 'DSN' }}}}}" > job.yaml
        dagster job execute -m odmkraken -j load_network -c job.yaml    
      env:
        EDGES_FILE: tests/network.edges.csv.zip
        NODES_FILE: tests/network.nodes.csv.zip
        DSN: ${{ steps.db.outputs.dsn_edmo_aoo }}
        PYTHONPATH: ./src
    
    - name: Run process_busdata on tests/testdata.zip
      shell: bash -l {0}
      run: |
        mkdir ${DAGSTER_HOME}
        cp ${TEST_FILE} 20230106180001_LUXGPS.csv.zip
        dagster job backfill -m odmkraken -j process_busdata --partitions 2023-01-01 --noprompt
      env:
        TEST_FILE: tests/testdata.csv.zip
        NETWORK_DB_DSN: ${{ steps.db.outputs.dsn_edmo_aoo }}
        PYTHONPATH: ./src
        DAGSTER_HOME: /home/runner/dagster_home