name: Run package tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: test
        cache-env: true
        environment-file: false
        channels: conda-forge,observatoire-mobilite
        extra-specs: |
          python=3.10
          pytest
          pytest-cov
          pytest-mock
          psycopg2=2.9.3
          dagster=0.16.10
          mapmatcher
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
    - name: Copy logfiles
      uses: actions/upload-artifact@v3
      with:
        name: code coverage
        path: cov.xml
