name: Run package tests

on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: test
        cache-env: true
        environment-file: false
        channels: conda-forge,observatoire-mobilite
        extra-specs: |
          python=${{ matrix.python-version }}
          pytest
          pytest-cov
          pytest-mock
          psycopg2
          dagster>=1.0.10
          mapmatcher
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --pastebin=failed --junitxml=./report.xml
    - name: Copy logfiles
      uses: actions/upload-artifact@v3
      with:
        name: test reports ${{ matrix.node-version }}
        path: |
          cov.xml
          report.xml
