name: Run package tests

on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: kartoza/postgis:14-3.1
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS_FILE: /run/secrets/pg_root_password
          ALLOW_IP_RANGE: 0.0.0.0/0
          POSTGRES_MULTIPLE_EXTENSIONS: postgis,postgis_topology,postgis_raster,pgrouting
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: test
        cache-env: true
        environment-file: false
        channels: conda-forge,observatoire-mobilite
        extra-specs: |
          python=${{ matrix.python-version }}
          pytest
          pytest-cov
          pytest-mock
          psycopg2
          dagster>=1.0.10
          mapmatcher
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --pastebin=failed --junitxml=./report.xml
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASS: postgres
    - name: Recover test report
      uses: actions/upload-artifact@v3
      with:
        name: odmkraken-py${{ matrix.python-version }}-pytest-report.xml
        path: report.xml
    - name: Recover coverage report
      uses: actions/upload-artifact@v3
      with:
        name: odmkraken-py${{ matrix.python-version }}-pytest-coverage.xml
        path: cov.xml
